/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TimeblockPostBodyInput
 */
export interface TimeblockPostBodyInput {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof TimeblockPostBodyInput
     */
    '$schema'?: string;
    /**
     * Days of the week where the timeblock reoccurs in binary form. STARTING ON MONDAY! Example is every week on Tuesday
     * @type {string}
     * @memberof TimeblockPostBodyInput
     */
    'Days'?: string | null;
    /**
     * Date to end
     * @type {string}
     * @memberof TimeblockPostBodyInput
     */
    'EndDate'?: string | null;
    /**
     * Time to end
     * @type {string}
     * @memberof TimeblockPostBodyInput
     */
    'EndTime': string;
    /**
     * Name for the timeblock
     * @type {string}
     * @memberof TimeblockPostBodyInput
     */
    'Name'?: string;
    /**
     * Does the timeblock reoccur. If this is set, days also needs to be set.
     * @type {boolean}
     * @memberof TimeblockPostBodyInput
     */
    'Recur'?: boolean;
    /**
     * Date to start
     * @type {string}
     * @memberof TimeblockPostBodyInput
     */
    'StartDate': string;
    /**
     * Time to start
     * @type {string}
     * @memberof TimeblockPostBodyInput
     */
    'StartTime': string;
    /**
     * The ID of the Tag
     * @type {number}
     * @memberof TimeblockPostBodyInput
     */
    'TagID'?: number;
}

