/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TimeblockPostOutputBody
 */
export interface TimeblockPostOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof TimeblockPostOutputBody
     */
    '$schema'?: string;
    /**
     * Id for new user
     * @type {number}
     * @memberof TimeblockPostOutputBody
     */
    'id': number;
}

