/* tslint:disable */
/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorModel } from '../models';
// @ts-ignore
import type { TimeblockGetOutputBody } from '../models';
// @ts-ignore
import type { TimeblockPostBodyInput } from '../models';
// @ts-ignore
import type { TimeblockPostOutputBody } from '../models';
/**
 * TimeblockApi - axios parameter creator
 * @export
 */
export const TimeblockApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get timeblock
         * @param {number} id Id for the timeblock you want to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTimeblock: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getTimeblock', 'id', id)
            const localVarPath = `/timeblock/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create new timeblock
         * @param {TimeblockPostBodyInput} timeblockPostBodyInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postTimeblock: async (timeblockPostBodyInput: TimeblockPostBodyInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'timeblockPostBodyInput' is not null or undefined
            assertParamExists('postTimeblock', 'timeblockPostBodyInput', timeblockPostBodyInput)
            const localVarPath = `/timeblock`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(timeblockPostBodyInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TimeblockApi - functional programming interface
 * @export
 */
export const TimeblockApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TimeblockApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get timeblock
         * @param {number} id Id for the timeblock you want to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTimeblock(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TimeblockGetOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTimeblock(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TimeblockApi.getTimeblock']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create new timeblock
         * @param {TimeblockPostBodyInput} timeblockPostBodyInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postTimeblock(timeblockPostBodyInput: TimeblockPostBodyInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TimeblockPostOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postTimeblock(timeblockPostBodyInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TimeblockApi.postTimeblock']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TimeblockApi - factory interface
 * @export
 */
export const TimeblockApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TimeblockApiFp(configuration)
    return {
        /**
         * 
         * @summary Get timeblock
         * @param {number} id Id for the timeblock you want to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTimeblock(id: number, options?: RawAxiosRequestConfig): AxiosPromise<TimeblockGetOutputBody> {
            return localVarFp.getTimeblock(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create new timeblock
         * @param {TimeblockPostBodyInput} timeblockPostBodyInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postTimeblock(timeblockPostBodyInput: TimeblockPostBodyInput, options?: RawAxiosRequestConfig): AxiosPromise<TimeblockPostOutputBody> {
            return localVarFp.postTimeblock(timeblockPostBodyInput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TimeblockApi - object-oriented interface
 * @export
 * @class TimeblockApi
 * @extends {BaseAPI}
 */
export class TimeblockApi extends BaseAPI {
    /**
     * 
     * @summary Get timeblock
     * @param {number} id Id for the timeblock you want to get
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TimeblockApi
     */
    public getTimeblock(id: number, options?: RawAxiosRequestConfig) {
        return TimeblockApiFp(this.configuration).getTimeblock(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create new timeblock
     * @param {TimeblockPostBodyInput} timeblockPostBodyInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TimeblockApi
     */
    public postTimeblock(timeblockPostBodyInput: TimeblockPostBodyInput, options?: RawAxiosRequestConfig) {
        return TimeblockApiFp(this.configuration).postTimeblock(timeblockPostBodyInput, options).then((request) => request(this.axios, this.basePath));
    }
}

